#Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

#Set environment variables for PostgreSQL
ENV POSTGRES_USER=root
ENV POSTGRES_DB=mydatabase

#The password will be provided at runtime
