enum TokenType {
  CREATE = "CREATE",
  QUBIT = "QUBIT",
  CONNECT = "CONNECT",
  IDENTIFIER = "IDENTIFIER",
  EQUALS = "EQUALS",
  COMMA = "COMMA",
  SEMICOLON = "SEMICOLON",
  LBRACKET = "LBRACKET",
  RBRACKET = "RBRACKET",
  PLUS = "PLUS",
  MINUS = "MINUS",
  NUMBER = "NUMBER",
  IMAGINARY_UNIT = "IMAGINARY_UNIT",
  WHITESPACE = "WHITESPACE"
}
